### ISSUE TITLE
ble_client do not work with pvvx_mithermometer

### ISSUE THREAD

**Issue by tomaszduda23** [OttoWinter/esphomeyaml#10317]
### The problem

There were several fixes related to https://github.com/esphome/issues/issues/5119. One of them caused regression. pvvx_ble_display time is not updated. It works sometimes though. In the past it was sync every night.

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

esp32doit-devkit-v1

### Component causing the issue

ble_client

### YAML Config

```yaml
ble_client:
- mac_address: "xyz"
  id: pvvx_ble_display
  on_passkey_request:
    then:
      - logger.log: "Authenticating with passkey"
      - ble_client.passkey_reply:
          id: pvvx_ble_display
          passkey: xxxxx

display:
- platform: pvvx_mithermometer
  ble_client_id: pvvx_ble_display
  update_interval: 24h
  validity_period: 0s
  disconnect_delay: 30s
  time_id: homeassistant_time
  id: display_bathroom
```

### Anything in the logs that might be useful for us?

```txt
[10:57:12][W][display.pvvx_mithermometer:072]: [xyz] Not connected to BLE client.  State update can not be written.
```
