### ISSUE TITLE
[Feature Request] Allow power_supply on sensor component

### ISSUE THREAD

**Issue by fusedsynapse** [OttoWinter/esphomeyaml#106]
I have a sensor which has to be powered from a separate power supply to my ESP8266. In order to minimise power consumption, I would like to be able to power off the supply when the sensor is not in use. I can see that on Output components a power_supply can be specified, but this does not appear to extend to sensor components.

Can the sensor component please be extended to support a power_supply?

Thanks for all your great work!

**Comment by OttoWinter** [comment]
Uhm, I don't really want to extend power supply to the sensor class because it would be very difficult to do with the existing architecture. You could, however, do something like this starting with the next version:

```yaml
sensor:
# This is the sensor you want to poll
- platform: ...
  id: my_sensor
  name: "The Sensor"
  # ... Setup your sensor platform
  update_interval: never  # esphomelib will never poll this sensor, we will do it ourselves.
# This is the template sensor that will control the power and updates the "real" sensor. 
- platform: template
  id: unused_sensor
  lambda: |-
    digitalWrite(23, HIGH);
    id(my_sensor).update();
    digitalWrite(23, LOW);
    return NAN;
```
