### ISSUE TITLE
JSON string in MQTT Birth and LWT Payloads

### ISSUE THREAD

**Issue by bwicks** [OttoWinter/esphomeyaml#11]
Hi,

I’m trying to use a JSON string in Birth and LWT payloads but getting an error regarding 
Mqtt: - Invalid config for [mqtt]: string value cannot be dictionary or list.

Is there some way of getting this to work?

**Comment by bwicks** [comment]
Here's my mqtt yaml for reference:

mqtt:
  broker: '192.168.1.143'
  username: 'home'
  password: 'kit'

  birth_message:
    topic: homebridge/to/set
    payload: {
 "name": "smokealarm1",
"service_name": "SmokeSensor",
 "characteristic": "SmokeDetected",
"value": 1
}
    qos: 1

  will_message:
    topic: homebridge/to/set
    payload: {
"name": "smokealarm1",
"service_name": "SmokeSensor",
"characteristic": "SmokeDetected",
"value": 0
}
    qos: 1

**Comment by OttoWinter** [comment]
Your JSON payload is being interpreted as a YAML mapping (like when you write `broker: '192.168.1.143'`). So esphomeyaml receives the configuration like this:

```yaml
mqtt:
  broker: '192.168.1.143'
  username: 'home'
  password: 'kit'
  birth_message:
    topic: homebridge/to/set
    payload:
      name: "smokealarm1"
      service_name: "SmokeSensor"
      characteristic: "SmokeDetected"
      value: 1
    qos: 1

  will_message:
    topic: homebridge/to/set
    payload:
      name: "smokealarm1"
      service_name: "SmokeSensor"
      characteristic: "SmokeDetected"
      value: 0
    qos: 1
```

The payload parameter, however, only accepts strings (like `'{"name":"smokealarm1", ...}'`).

So your configuration should look like this:

```yaml
mqtt:
  # ...
  birth_message:
    topic: homebridge/to/set
    payload: >-
      {
        "name": "smokealarm1",
        "service_name": "SmokeSensor",
        "characteristic": "SmokeDetected",
        "value": 1
      }
    qos: 1
  will_message:
    topic: homebridge/to/set
    payload: >-
      {
        "name": "smokealarm1",
        "service_name": "SmokeSensor",
        "characteristic": "SmokeDetected",
        "value": 0
      }
    qos: 1
```

The `>-` keeps the YAML parser from interpreting the value as a dictionary and makes it use everything indented in there as a string.

However, I just noticed above payload does not work because I don't escape the payload parameter when generating C++ code. I've now fixed the bug and it will be in the next esphomeyaml release. For now, you can do this

```yaml
mqtt:
  # ...
  birth_message:
    topic: homebridge/to/set
    payload: "{\\042name\\042:\\042smokealarm1\\042,\\042service_name\\042:\\042SmokeSensor\\042,\\042characteristic\\042:\\042SmokeDetected\\042,\\042value\\042:1}"
    qos: 1
  will_message:
    topic: homebridge/to/set
    payload: "{\\042name\\042:\\042smokealarm1\\042,\\042service_name\\042:\\042SmokeSensor\\042,\\042characteristic\\042:\\042SmokeDetected\\042,\\042value\\042:0}"
    qos: 1
```
