### ISSUE TITLE
Dimmer with single button: on_click?

### ISSUE THREAD

**Issue by balk77** [OttoWinter/esphomeyaml#111]
Hi, I would like to attach a momentary switch to an ESP32 to control a dimmable light.

- short press: toggle on/off
- long press: decrease or increase brightness

Is that possible with this very nice project? Could use 4 steps to cycle through various brightness settings? Or can I create a `while "on_click" == true` loop?

```
binary_sensor:
  - platform: gpio
    on_press:
      then:
        - switch.toggle:
            id: relay_1
    on_click:
      min_length: 0ms
      max_length: 999ms
      then:
        - switch.brightness_1
    on_click:
      min_length: 1000ms
      max_length: 1999ms
      then:
        - switch.brightness_2
    etc....
```
