### ISSUE TITLE
esphomeyaml-edge - pn532 component unable to compile

### ISSUE THREAD

**Issue by magnusoverli** [OttoWinter/esphomeyaml#114]
Created a template .yaml-file using the esphomeyaml dashboard, running edge-version. Edited the yaml-file to add the pn532 RFID-sensor (copy-paste from the docs) so that it looked like this:
```
esphomeyaml:
  name: musikkleser_v2
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'IoT'
  password: 'xxxxxxxxx'

mqtt:
  broker: '10.0.2.171'
  username: 'xxxxxxxxx'
  password: 'xxxxxxxxxxx'

# Enable logging
logger:

ota:
  password: 'xxxxxxxxx'

spi:
  clk_pin: D0
  miso_pin: D1
  mosi_pin: D2

pn532:
  cs_pin: D3
  update_interval: 1s

binary_sensor:
  - platform: pn532
    uid: 74-10-37-94
    name: "PN532 NFC Tag"
```

It validates OK but is unable to compile.
Log output:
```
INFO [esphomeyaml.config] Reading configuration...
INFO [esphomeyaml.__main__] Generating C++ source...
INFO [esphomeyaml.__main__] Compiling app...
INFO [esphomeyaml.__main__] Running:  platformio run -d config/musikkleser_v2
Processing musikkleser_v2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
SYSTEM: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 32 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphomelib> 1.7.0 #bd07644
|   |-- <AsyncMqttClient> 0.8.2
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP Async WebServer> 1.1.1
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <FastLED> 3.1.8 #d416194
|   |   |-- <EspSoftwareSerial> 3.4.1
|   |-- <ArduinoOTA> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ESP8266mDNS>
|   |   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <Wire> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/musikkleser_v2/src/main.cpp.o
Compiling .pioenvs/musikkleser_v2/lib4d9/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/musikkleser_v2/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs/musikkleser_v2/lib4d9/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pioenvs/musikkleser_v2/lib4d9/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pioenvs/musikkleser_v2/lib4d9/ESP8266WiFi/ESP8266WiFiScan.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:21:28: error: 'class esphomelib::Application' has no member named 'init_spi'
auto *spicomponent = App.init_spi(16);
^
src/main.cpp:23:44: error: 'class esphomelib::Application' has no member named 'make_pn532_component'
auto *binary_sensor_pn532component = App.make_pn532_component(spicomponent, 0, 1000);
^
*** [.pioenvs/musikkleser_v2/src/main.cpp.o] Error 1
========================== [ERROR] Took 3.43 seconds ==========================
```
