### ISSUE TITLE
Feature request: (GPIO) switch inverted option

### ISSUE THREAD

**Issue by apeeters** [OttoWinter/esphomeyaml#14]
Please add an inverted option to (GPIO) switch, similar to (GPIO) output.

**Comment by OttoWinter** [comment]
For the *GPIO* switch, that's already possible 🙈

```yaml
switch:
  - platform: gpio
    name: "Some Name"
    pin:
      number: 13
      inverted: false
```

But I guess I could expand it to all switch platforms.
