### ISSUE TITLE
WPA2 enterprise on pico W results in bootloop

### ISSUE THREAD

**Issue by JoramQ** [OttoWinter/esphomeyaml#14743]
### The problem

I can configure a WPA2 enterprise wifi network and the code is compiling for a Pico W. When running the code the device looks in a boot loop because i cannot see logs and the serial communication keeps resetting.

Is it even possible to use WPA2 enterprise on a pico? The results on google don't look so promising.
Is it possible to give a warning and prevent compiling when WPA2 enterprise is used for a pico?

### Which version of ESPHome has the issue?

2023.6

### What type of installation are you using?

Docker

### What platform are you using?

RP2040

### Board

Pico W

### Component causing the issue

wifi

### Example YAML snippet

```yaml
wifi:
  fast_connect: True
  networks:
  - ssid: ssidname
    hidden: True
    eap: 
      username: username
      password: password
```
