### ISSUE TITLE
Pico W I2C1 not working

### ISSUE THREAD

**Issue by z-eh** [OttoWinter/esphomeyaml#14742]
### The problem

I try to use an ina219 with my Pico W and ESPHome.
It wired to GP6 and GP7 which is the I2C1 on the Pico W.
When I configure this in yaml, it stops booting correctly.
No usable logs or anything, just simply not start correctly.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2

### What platform are you using?

RP2040

### Example YAML snippet

```yaml
i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

sensor:
  - platform: dht
    pin: 2
    model: DHT22
    temperature:
      name: "Children's Room Temperature"
      filters:
        offset: -3.0
    humidity:
      name: "Children's Room Humidity"
    update_interval: 60s
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 4.18V
    max_current: 0.6A
    update_interval: 60s
```

**Comment by rubenbaldewsing** [comment]
Same with using I2C_1 on GPIO2/3 (SDA/SCL)

**Comment by rubenbaldewsing** [comment]
same issue probably: https://github.com/esphome/issues/issues/5290

**Comment by rubenbaldewsing** [comment]
@jesserockz this issue is still a big problem for people that are not able to use I2C_0 with default config on the RP2040. I2C is just not working when using the non default configuration sadly.

Please remove the `stale` tag.

**Comment by rubenbaldewsing** [comment]
https://github.com/esphome/esphome/blob/dev/esphome/components/i2c/i2c_bus_arduino.cpp#L28-L35

The problem is that the wrong 'Wire' is selected. It is based on the order/amount of I2C busses defined, not what pins are being used.

Temporary fix, define 2 busses in the right order:

``` yaml
i2c:
  - id: bus_0
    sda: GPIO20
    scl: GPIO21
  - id: bus_1
    sda: GPIO2
    scl: GPIO3
```
