### ISSUE TITLE
pn532 - native ability to send tag as mqtt topic payload w/o registering all tags as binary sensors

### ISSUE THREAD

**Issue by wuub** [OttoWinter/esphomeyaml#187]
**Is your feature request related to a problem? Please describe.**
Yes. I need to send IDs of scanned RFID tags to MQTT topic. This topic is then configured in homeassistant  to work as trigger for a python_script.   

Basically I'm recreating this: https://www.youtube.com/watch?v=AvCseOQidSw

Since there's no easy way to achieve this in esphomeyaml, I'm using a horrendous hack of generating my config using jinja2 template :)
```yaml
switch:
  - platform: gpio
    pin: 16
    id: buzzer

binary_sensor:
{% for tag in tags %}
  - platform: pn532
    uid: {{ tag }}
    id: 'tag{{tag | replace('-', '')}}'
    on_press:
      - mqtt.publish:
          topic: nfc01/nfc_tag/on_press
          payload: '{{tag}}'
      - switch.turn_on: 
          id: buzzer
    on_release:
      - switch.turn_off: 
          id: buzzer

{% endfor %}
```

The problem is,  instead of 21 cards I acquired a tiny bit more and it will be a massive PITA to set up this way. 

![cards](https://user-images.githubusercontent.com/588857/47042470-a09b6d00-d18b-11e8-8e4a-8e4edfe5a08e.jpeg)

**Describe the solution you'd like**

I thought about different solutions, I think that placing `on_new_tag` somewhere would be the most flexible, but this cannot be added to `binary_sensor` (it makes no sense, what should happen if there are more than one of those).  
I guess this makes the most sense, but I don't know if it's doable:

```yaml
pn532:
  ...
  on_new_tag:
      - mqtt.publish:
          topic: nfc01/nfc_tag/on_press
          payload: !lambda "pn532.last_tag"
```

I dunno. I'm new here :)
**Additional context**
I know I can just whip out platformio and code this myself. But I would like to standardize on esphomeyaml, I like it.  Also the same lolin32 is looking at my Xiaomi Mija Plant Sensor, I don't want my plant to die :)
