### ISSUE TITLE
error during compilation when Installing toolchain-xtensa32

### ISSUE THREAD

**Issue by oncleben31** [OttoWinter/esphomeyaml#19]
Trying to set my first sensor with esphomeyaml, I'm creating a dallas component base yaml file.

When trying to compile, I have the following error:
```
PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
Error: Could not find a version that satisfies the requirement '~2.50200.0' for your system 'linux_armv7l'
```

yaml file: 
```
esphomeyaml:
  name: capteur_piscine
  platform: ESP32
  board: lolin32

wifi:
  ssid: '####'
  password: '#####'

mqtt:
  broker: '192.168.1.28'
  username: '####'
  password: '####'

# Enable logging
logger:

ota:
  password: '#######'

# Example configuration entry
dallas:
  - id: dallas_hub1
    pin: 4

# Individual sensors
sensor:
  - platform: dallas
    dallas_id: "dallas_hub1"
    address: 0x28FF88A9C117049C
    resolution: 10
    name: "Température Piscine"
```

Hardware/Software: 

- Raspberry Pi 3
- HassIO 0.69.1
- using esphomeyaml thru the HassIO-addon (https://github.com/OttoWinter/esphomeyaml-hassio)
