### ISSUE TITLE
Cannot be used if action in mqtt.on_message trigger

### ISSUE THREAD

**Issue by r-jordan** [OttoWinter/esphomeyaml#203]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP8266

**Affected component:**
https://esphomelib.com/esphomeyaml/components/mqtt.html#mqtt-on-message

**Description of problem:**
I would like to make some action depending on the payload of a mqtt message received.
When a conditional "if" action is used inside an mqtt.on_message trigger a compiling error is showed.

**Problem-relevant YAML-configuration entries:**
```yaml
mqtt:
  broker: 'xxx'
  username: 'xxx'
  password: 'xxx'
  discovery: False
  on_message:
    topic: devicex/ota_mode
    then:
      - if:
          lambda: 'return strcmp(x,"ON")==0;'
        then:
          - deep_sleep.prevent:
              id: deep_sleep_1
```

**Traceback (if applicable):**
```
Failed config
 mqtt:
   - Invalid config for [mqtt]: Cannot have two actions in one item. Key if overrides then! for dictionary value @ data['on_message']['then']. Got [OrderedDict([('if', OrderedDict([('lambda', 'return strcmp(x,"ON")==0;')])), ('then', [OrderedDict([('deep_sleep.prevent', OrderedDict([('id', 'deep_sleep_1')]))])]), ('action_id', None)])]. (See devicex.yaml, line 16). 
    - broker: xxx
      discovery: False
      on_message: [source devicex.yaml:21]
        then: ?
          - action_id: None
            if: [source devicex.yaml:24]
              lambda: return strcmp(x,"ON")==0;
            then: ?
              - deep_sleep.prevent: [source devicex.yaml:27]
                  id: deep_sleep_1
        topic: devicex/ota_mode
      password: xxx
      username: xxx
```

**Additional information:**

**Comment by stoinov** [comment]
I am unable to make this one work:
```yaml
  on_message:
    topic: test8266/light/ledstrip/switch
    then:
      - if:
        condition:
          lambda: 'x == "ON";'
        then:
          - light.turn_on:
              id: ledstrip
              brightness: 100
        else:
          - light.turn_off: ledstrip

```

**Comment by r-jordan** [comment]
It's compiling for me with this:

``lambda: 'return x == "ON";'``

For lights is more convenient to use any light component for example:

https://esphomelib.com/esphomeyaml/components/light/monochromatic.html

**Comment by OttoWinter** [comment]
@stoinov Please see my comment from before, everything in the `if:` block needs to be indented

```yaml
  on_message:
    topic: test8266/light/ledstrip/switch
    then:
      - if:
          condition:
            lambda: 'x == "ON";'
          then:
            - light.turn_on:
                id: ledstrip
                brightness: 100
          else:
            - light.turn_off: ledstrip
```
