### ISSUE TITLE
FastLED SPI Light - effects in HA not working

### ISSUE THREAD

**Issue by try65do** [OttoWinter/esphomeyaml#204]
**Operating environment (Hass.io/Docker/pip/etc.):**
 Docker

**ESP (ESP32/ESP8266/Board/Sonoff):**
esp8266 / WeMos Di Mini

**Affected component:**

FastLED SPI Light

https://esphomelib.com/esphomeyaml/components/light/fastled_spi.html

**Description of problem:**

Effects not present in Home Assistant after auto discovery, all other aspects work as expected.

**Problem-relevant YAML-configuration entries:**
```yaml
light: 
  - platform: fastled_spi
    chipset: WS2801
    clock_pin: GPIO2
    data_pin: GPIO3
    name: "Kitchen Lights"
    num_leds: 58
    rgb_order: RGB
    effects:
      - fastled_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
```

**Traceback (if applicable):**

```

```

**Additional information:**

Discovery message:
```json
{  
   "brightness":true,
   "rgb":true,
   "flash":true,
   "name":"Kitchen Lights",
   "platform":"mqtt_json",
   "state_topic":"kitchen_lights/light/kitchen_lights/state",
   "command_topic":"kitchen_lights/light/kitchen_lights/command",
   "availability_topic":"kitchen_lights/status"
}
```
