### ISSUE TITLE
BME280

### ISSUE THREAD

**Issue by fabaff** [OttoWinter/esphomeyaml#22]
Using a BME280 with the following configuration is not able to retrieve the humidity.

```yaml
i2c:
  sda: 21
  scl: 22
  scan: False

sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    address: 0x76
    update_interval: 15s
```
Debug:

```bash
[C][sensor.bme280:095]: Setting up BME280...
[C][sensor.bme280:096]:     Address: 0x76
[C][sensor.bme280:126]:     Temperature Oversampling: 16x
[C][sensor.bme280:127]:     Pressure Oversampling: 16x
[C][sensor.bme280:128]:     Humidity Oversampling: 16x
[C][sensor.bme280:129]:     IIR Filter: OFF
[...]
[D][sensor.bme280:177]: Got temperature=26.0°C pressure=952.6hPa humidity=0.0
[D][sensor.mqtt:038]: 'Temperature': Pushing out value 25.980000 with accuracy 1
[D][sensor.mqtt:038]: 'Pressure': Pushing out value 952.551331 with accuracy 1
[D][sensor.mqtt:038]: 'Humidity': Pushing out value 0.000000 with accuracy 1
```

Sorry, I have only one of those sensors at hand at the moment.
