### ISSUE TITLE
Question: Best way to do action before adc measurement

### ISSUE THREAD

**Issue by escoand** [OttoWinter/esphomeyaml#242]
I use a thermistor connected to ADC and want to avoid it is heating up while waiting for the next cycle.
What is the best way to have the GPIO set to 0 all the time and just to 1 in case of measuring?

**Comment by OttoWinter** [comment]
That's what `update_interval: never` is for. You can work around the whole thing like this:

```yaml
switch:
- platform: gpio
  id: adc_on
  pin: GPIO23
sensor:
- platform: adc
  name: ADC Sensor
  id: my_adc
  update_interval: never

# Template sensor used here for the update interval feature, but it's not publishing any values
# Any component that has update interval could be used here (for example script would also work)
- platform: template
  lambda: |-
    id(adc_on).turn_on();
    id(my_adc).update();
    id(adc_on).turn_off();
    return {};
  update_interval: 15s
```
