### ISSUE TITLE
[Suggestion / Feature Request] Handling outputs directly in components

### ISSUE THREAD

**Issue by Melkor82** [OttoWinter/esphomeyaml#243]
Hello, I've very new to this world and I really love it. Had my first light on yesterday. 
I'm trying to implement a monochromatic light today and
```
output:
- platform: ledc
  id: pin18
  pin: 18

light:
- platform: monochromatic
  name: "striscia"
  id: striscia
  output: pin18
```
that leads to a compile cpp lines like 

```
output::LEDCOutputComponent *pin18 = App.make_ledc_output(18);
::Application::MakeLight _application_makelight_2 = App.make_monochromatic_light("striscia", pin18);
```
after many lights set it is quite difficult to follow wich light activate which output. Wouldn't be more easy to handle outputs directly in lights section? Something like:

```
light:
- platform: monochromatic
  name: "striscia"
  id: striscia
  output: 
  - platform: gpio
    pin: 18
```
then it could be implemented directly as :

`::Application::MakeLight _application_makelight_2 = App.make_monochromatic_light("striscia", App.make_ledc_output(18));`
