### ISSUE TITLE
L298 Dual H-Bridge DC Motor Controller

### ISSUE THREAD

**Issue by Qu3uk** [OttoWinter/esphomeyaml#247]
**What new integration would you wish to have?**

L298 Dual H-Bridge DC Motor Controller
https://www.sparkfun.com/products/9670
**If possible, provide a link to an existing library for the integration:**
https://github.com/AndreaLombardo/L298N ?
**Is your feature request related to a problem? Please describe.**
This is what I have and rather not buy something else to convert an old project etc
**Additional context**

**Comment by OttoWinter** [comment]
Yes, that integration is planned - and it wouldn't even be too hard to integrate.
The issue is that a whole "motor" abstraction layer would have to be created first and that's a lot of work since there are so many types of motors.
For now, you can also control it using the PWM components. For example

```yaml
output:
- platform: gpio
  pin: D1
  id: direction_pin
- platform: esp8266_pwm  # or ledc if on ESP32
  pin: D2
  id: speed_pin

# In some call:
# Set to forward dir
- output.turn_on: direction_pin
# Turn on motor
- output.set_level:
    id: speed_pin
    level: 100%
# Let motor drive for a big
- delay: 1s
# Turn off motor
- output.turn_off: speed_pin
# Repeat for Oóther direction, this time with turning off the direction pin
```
