### ISSUE TITLE
bme280 data not available after power cycle.  Current HASSIO on RPi3

### ISSUE THREAD

**Issue by questrov** [OttoWinter/esphomeyaml#251]
**Operating environment (Hass.io/Docker/pip/etc.):**
wemos D1mini with bme280 and Dallas temp

**ESP (ESP32/ESP8266/Board/Sonoff):**
<!-
Please provide details about which ESP you're using.
-->

**Affected component:**

**Description of problem:**
All works OK but after power cycle to wemosD1 data not available in HA.  Debug page no data, just the header.  Restart HA and all OK.  

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: wemo_bme280
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'my wifi'
  password: 'my password'
  manual_ip:
    static_ip: mystaticip
    gateway: mygateway
    subnet: 255.255.255.0

mqtt:
  broker: 'myip'
  username: 'myusername'
  password: 'mypassword'
  discovery: true
  discovery_prefix: homeassistant

# Enable logging
logger:

ota:

i2c:
  sda: D2
  scl: D1
  scan: False
  
dallas:
  - pin: D4
  
sensor:
  - platform: bme280
    temperature:
      filters:
        - offset: -1.5
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 15s
    
  - platform: dallas
    index:  0
    name: "planter temperature"
    
  - platform: wifi_signal
    name: "Planter WiFi Signal Sensor"
    update_interval: 15s
```

**Traceback (if applicable):**

```

```

**Additional information:**
