### ISSUE TITLE
button configuration: failed config

### ISSUE THREAD

**Issue by roadfox** [OttoWinter/esphomeyaml#252]
**Operating environment (Hass.io/Docker/pip/etc.):**
  esphomeyaml Version: 1.9.3

**ESP (ESP32/ESP8266/Board/Sonoff):**
  platform: ESP32
  board: m5stack-core-esp32

**Affected component:**
  binary_sensor

**Description of problem:**
The Module has 3 Buttons, they work in a basic configuration, but are invertet, trying to change the config results in failed config errors

**Problem-relevant YAML-configuration entries:**
working config:
```yaml
binary_sensor:
  - platform: gpio
    name: "Button1"
    pin: 38
```
output when pressing and releasing the button:
```
[11:20:36][D][binary_sensor:027]: 'Button1': Sending state OFF
[11:20:36][D][binary_sensor:027]: 'Button1': Sending state ON
```

so i tried to change the config to:
```yaml
binary_sensor:
  - platform: gpio
    name: "Button1"
    pin:
      number: 38
      inverted: True
```
but this results in the following config error:
```
Failed config
 binary_sensor.gpio:
   - Invalid config for [binary_sensor.gpio]: ESP32: Pin 38 (34-39) can only be used as input pins. for dictionary value @ data['pin']['number']. Got 38. (See .\esp32-wemos-epa
per29.yaml, line 67).
    - platform: gpio
      name: Button1
      pin: [source .\esp32-wemos-epaper29.yaml:70]
        inverted: True
        number: 38
```

**Additional information:**
also adding:
```yaml
mode: INPUT
or
mode: INPUT_PULLUP
```
ends with the same error message
