### ISSUE TITLE
Unexpected template switch restoration behavior

### ISSUE THREAD

**Issue by brandond** [OttoWinter/esphomeyaml#268]
**Operating environment (Hass.io/Docker/pip/etc.):**
virtualenv+pip from git

**ESP (ESP32/ESP8266/Board/Sonoff):**
esp01_1m / Tuya smart plug (bicolor LED, relay, pushbutton switch)

**Affected component:**
https://esphomelib.com/esphomeyaml/components/switch/template.html

**Description of problem:**
When used with `restore_state: true`, the template switch turns itself on every boot, regardless of whether it was on or off. When used with `restore_state: false`, it seems like the GPIO switch tries to remember its state (which the documentation says it will) and turn on or off depending on what it last was, but the light does not - which results in the light and switch being out of sync.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: demoplug
  platform: ESP8266
  board: esp01_1m
  arduino_version: dev
  esphomelib_version: dev
  board_flash_mode: dout

wifi:
  ssid: 'ssid'
  password: 'password'

mqtt:
  broker: 'broker'
  username: ''
  password: ''

logger:

sensor:
  - platform: wifi_signal
    name: "Demo Plug WiFi Signal"
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 4

switch:
 - platform: gpio
   id: relay0
   pin:
     number: 14
     mode: OUTPUT
 - platform: template
   id: template0
   name: "Demo Plug Power"
   turn_on_action:
     - light.turn_on: led0_light
     - switch.turn_on: relay0
   turn_off_action:
     - light.turn_off: led0_light
     - switch.turn_off: relay0
   optimistic: true

binary_sensor:
  - platform: gpio
    id: button0
    pin:
      number: 4
      mode: INPUT
    on_press:
      then:
        - switch.toggle: template0

status_led:
  pin:
    number: 12
    mode: OUTPUT
    inverted: true

output:
  - platform: esp8266_pwm
    id: led0_output
    pin:
      number: 13
      mode: OUTPUT
      inverted: true

light:
  - platform: monochromatic
    id: led0_light
    output: led0_output
```
