### ISSUE TITLE
CSE7766 update_interval compile error

### ISSUE THREAD

**Issue by Mynasru** [OttoWinter/esphomeyaml#270]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io 0.84.4
ESPHomeYalm 1.9.3

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP8266 (SonOff POW R2)

**Affected component:**
[CSE7766](https://esphomelib.com/esphomeyaml/components/sensor/cse7766.html)

**Description of problem:**
My yalm is valid, but does not compile when I add `update_interval: 5s`. When removed it compiles and works without a problem.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: cse7766
    current:
      name: "Sonoff POW R2 Current"
    voltage:
      name: "Sonoff POW R2 Voltage"
    power:
      name: "Sonoff POW R2 Power"
    update_interval: 5s
```

**Log:**

```
Compiling .pioenvs/sonoff_pow_r2/src/main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:30:92: error: no matching function for call to 'esphomelib::Application::make_cse7766(esphomelib::UARTComponent*&, int)'
sensor::CSE7766Component *sensor_cse7766component = App.make_cse7766(_uartcomponent, 5000);
^
src/main.cpp:30:92: note: candidate is:
In file included from src/main.cpp:2:0:
.piolibdeps/esphomelib/src/esphomelib/application.h:921:29: note: esphomelib::sensor::CSE7766Component* esphomelib::Application::make_cse7766(esphomelib::UARTComponent*)
sensor::CSE7766Component *make_cse7766(UARTComponent *parent);
^
.piolibdeps/esphomelib/src/esphomelib/application.h:921:29: note:   candidate expects 1 argument, 2 provided
```
