### ISSUE TITLE
MQTT on_message fails at build when using payload

### ISSUE THREAD

**Issue by arnie580** [OttoWinter/esphomeyaml#271]
Using the on_message > payload option fails at build time:

`C:\Users\arnie>esphomeyaml conservatory.yaml run
�[32mINFO Reading configuration...�[0m
Failed config
mqtt:

Invalid config for [mqtt]: [payload] is an invalid option for [mqtt]. Check: mqtt->on_message->0->payload. (See conservatory.yaml, line 10).
- broker: 192.168.0.253
on_message: ?
payload: 1
then: ?
output.turn_on: cons_light_status
topic: conservatory/light/status
password:
username:`
This is my yaml:

```
mqtt: 
  broker: '192.168.0.253'
  username: '' 
  password: '' 
  on_message: 
    - topic: "conservatory/light/status"
      payload: '1' 
      then: 
        - output.turn_on: cons_light_status
```

If the payload option is not used it compiles as expected.

Version 1.9.0 & 1.9.3 using windows command line.
