### ISSUE TITLE
Reusable Firmware Builds / Device+Component Name Templating

### ISSUE THREAD

**Issue by brandond** [OttoWinter/esphomeyaml#278]
**Is your feature request related to a problem/use-case? Please describe.**
I would like to be able to flash the same firmware on multiple identical devices and have device and component names auto-generated based on the device ID.

**Describe the solution you'd like**
I would like to auto-name the device as well as the sensors/switches using some portion of the device ID or MAC address. Something like this perhaps, where the `{id}` portion of the device and component names were replaced at runtime with the last few characters of the id.

```yaml
esphomeyaml:
  name: 'smartplug_{id}'
  platform: ESP8266
  board: esp01_1m
  arduino_version: dev
  esphomelib_version: dev
  board_flash_mode: dout
  build_path: plugs

wifi:
  ssid: 'ssid'
  password: 'password'

mqtt:
  broker: '10.0.1.27'
  discovery_prefix: homeassistant
  username: ''
  password: ''

logger:

sensor:
  - platform: wifi_signal
    name: "Smart Plug {id} WiFi Signal"
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 4

switch:
 - platform: gpio
   id: switch0
   pin:
     number: 14
     mode: OUTPUT
 - platform: template
   id: template0
   icon: "mdi:power-plug"
   name: "Smart Plug {id} Power"
   restore_state: yes
   turn_off_action:
     - light.turn_off:
         id: led0_light
         transition_length: 0.5s
     - switch.turn_off:
         id: switch0
   turn_on_action:
     - light.turn_on:
         id: led0_light
         transition_length: 0.5s
     - switch.turn_on:
         id: switch0
   lambda: "return id(switch0).state;"

binary_sensor:
  - platform: gpio
    id: button0
    pin:
      number: 4
      mode: INPUT
    on_press:
      then:
        - switch.toggle:
            id: template0

status_led:
  pin:
    number: 12
    mode: OUTPUT
    inverted: true

output:
  - platform: esp8266_pwm
    id: led0_output
    pin:
      number: 13
      mode: OUTPUT
      inverted: true

light:
  - platform: monochromatic
    id: led0_light
    output: led0_output
```

**Additional context**
I have a number of 'Tuya Smart' WiFi plugs that have an ESP-01M embedded in them. I've successfully reflashed them with esphomelib, but the process of building the firmware for each of them is somewhat irritating, in that I have to open the YAML file, replace all instances of '01' with '02', compile, flash, repeat until they're all done. Additionally, I have to manually keep track of which is which lest I accidentally flash more than one as 'Smart Plug 01'.

It would save me a great deal of time and manual device tracking if I could just build the firmware once and flash it to all of the devices, and have them auto-name themselves.
