### ISSUE TITLE
Current SNTP time for device

### ISSUE THREAD

**Issue by meijerwynand** [OttoWinter/esphomeyaml#283]
**Is your feature request related to a problem/use-case? Please describe.**
Display the current SNTP time as a component. To be able to see what the current time is on the device. In case of a failed SNTP update to be easier to identify or troubleshoot the issue.

**Describe the solution you'd like:**
Similar to the wifi signal or uptime sensors, 
```
sensor:
  - platform: sntp_time
    name: "esp_xxx_system_sntp_time"
    id: esp_xxx_system_sntp_time
    format_time: "%c"
    update_interval: 15s
```

**Additional context:**
 I have been unsuccessful to display the current time into HA using lamba's or to find a good/working example. If such a option is possible, please supply the correct method / code how to achieve it and I will gladly add to the cookbook docs.

Thanks
