### ISSUE TITLE
No connection to hidden SSID

### ISSUE THREAD

**Issue by MattXcz** [OttoWinter/esphomeyaml#320]
**Operating environment (Hass.io/Docker/pip/etc.):** pip

**ESP (ESP32/ESP8266/Board/Sonoff):** esp8266

**Affected component:** WIFI

**Description of problem:**
After upgrade ESP8266 can't connect to SSID that is hidden.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
wifi:
  ssid: 'Serverovna'
  password: '(secret...)'
```

**Traceback (if applicable):**

```

```

**Additional information:**
