### ISSUE TITLE
ESP offline after OTA update 

### ISSUE THREAD

**Issue by romanpeters** [OttoWinter/esphomeyaml#328]
**Operating environment (Hass.io/Docker/pip/etc.):** Hass.io, ESPHome add-on v1.10.0
 

**ESP (ESP32/ESP8266/Board/Sonoff):** Sonoff

**Description of problem:**
I decided to replace MQTT with the new Native API for Home Assistant, on a Sonoff I've had up and running for a while. I removed the MQTT configuration and added `api:` (without a password), through the Hass.io add-on. Validation went through and the Sonoff was online.
After compiling and uploading, I got a warning that it used the Legacy OTA method as a fallback (I hadn't updated this Sonoff in a while, so expected behaviour I guess).
After that, the logs said the upload was a success, however it would repeatedly warn me that it couldn't connect to the API.
Closing the upload screen, showed the Sonoff now being offline in the Hass.io add-on.
I tried restarting the Sonoff, by unplugging it from the socket and back in, but to no avail.
Once plugged in, the green LED on the Sonoff turns on for a fraction of a second, then turns off.
I tried to connect to the Sonoff through Home Assistant, but got a connection error.
I tried to ping the Sonoff, but got request timeout and host is down.

It looks like the Sonoff has become completely unresponsive.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: sonoff2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'redacted'
  password: 'redacted'

api:

logger:

ota:
  password: 'redacted'

switch:
  - platform: gpio
    name: "Heater"
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "Heater LED"
    output: basic_green_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Heater Button"
  - platform: status
    name: "Sonoff Status"
```

**Traceback (if applicable):**
Running "Show Logs" in the Hass.io add-on repeats this warning:

```
INFO Connecting to sonoff2.local:6053 (10.10.10.196)
WARNING Couldn't connect to API (Error connecting to 10.10.10.196: [Errno 113] No route to host). Trying to reconnect in 1 seconds
```

**Additional information:**
