### ISSUE TITLE
Switch component not working after update

### ISSUE THREAD

**Issue by talondnb** [OttoWinter/esphomeyaml#331]
I'm having trouble getting a gpio switch to work after the update to 0.85 / 1.10.0. My config below:

```
esphomeyaml:
  name: garage_opener
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'xxx'
  password: 'xxx'
  manual_ip:
    static_ip: 192.168.0.131
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.201'
  username: 'xxx'
  password: 'xxx'

# Enable logging
logger:

ota:
  password: 'xxx'

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      inverted: True
      mode: INPUT_PULLUP
    name: "Garage Door Closed"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    device_class: garage_door
    
switch:
  - platform: gpio
    name: "Garage Door Trigger"
    pin: D7

sensor:
  - platform: ultrasonic
    filters:
      - filter_nan:
    trigger_pin: D5
    echo_pin: D6
    update_interval: 30s
    name: "Ultrasonic Car Sensor"

```

This configuration worked fine in the previous HA and 1.9.3. I've tried adding an 'inverted: yes' to the switch component, just to see if it boots inverted and it does. I can see the component appear in HA but unable to trigger it and logs don't seem to show the mqtt topic when posted either.

Other components seems to function fine in the above config. Only the switch component appears affected.

I posted to the recently closed issue about covers, but my issue seems to only relate to the switch component.
