### ISSUE TITLE
ESP32 and Mi Flora routine fails on dependency libstdc++

### ISSUE THREAD

**Issue by unw1red** [OttoWinter/esphomeyaml#336]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io

Ubuntu 18.04 LTS VM running on QNAP. Docker running to support Hass.io.
**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP32

HiLetGO ESP32 Dev Kit
**Affected component:**

Mi Flora routine

**Description of problem:**
Compilation errors out with dependency issue

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
`esphomeyaml:
  name: miflora_office
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'Gr1ff1n-1X'
  password: 'bxxxxxxx'

mqtt:
  broker: '192.168.27.20'
  username: 'ha'
  password: 'xxxxxxxxxx'

# Enable logging
logger:

ota:
``

**Traceback (if applicable):**
<!--
Please copy the traceback here if compilation is failing. If possible, also connect to the ESP and copy its logs into the backticks.
-->
```
Compiling .pioenvs/miflora_office/lib174/FastLED/FastLED.cpp.o
Compiling .pioenvs/miflora_office/lib174/FastLED/bitswap.cpp.o
Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++)
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znam: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdlPv: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_newchunk: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: obstack_free: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_begin: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdaPv: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znwm: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_memory_used: symbol not found
*** [.pioenvs/miflora_office/lib174/FastLED/FastLED.cpp.o] Error 127
Error loading shared library libstdc++.so.6: No such file or directory (needed by /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++)
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znam: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdlPv: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_newchunk: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: obstack_free: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_begin: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _ZdaPv: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _Znwm: symbol not found
Error relocating /root/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++: _obstack_memory_used: symbol not found
*** [.pioenvs/miflora_office/lib174/FastLED/bitswap.cpp.o] Error 127
========================== [ERROR] Took 32.97 seconds ==========================
```

**Additional information:**
