### ISSUE TITLE
custom output - [type] is an invalid option for [output.custom]

### ISSUE THREAD

**Issue by alessiocurri** [OttoWinter/esphomeyaml#343]
**Operating environment (Hass.io/Docker/pip/etc.):**

pip in a python2.7 virtualenv on Ubuntu 18.04

```
Package          Version   
---------------- ----------
backports-abc    0.5       
bottle           0.12.16   
certifi          2018.11.29
chardet          3.0.4     
click            5.1       
colorama         0.4.1     
colorlog         4.0.2     
ecdsa            0.13      
esphomeyaml      1.10.1    
esptool          2.6       
futures          3.2.0     
idna             2.8       
paho-mqtt        1.4.0     
pip              18.1      
platformio       3.6.3     
protobuf         3.6.1     
pyaes            1.6.1     
pyserial         3.4       
pytz             2018.9    
PyYAML           3.13      
requests         2.21.0    
semantic-version 2.6.0     
setuptools       40.6.3    
singledispatch   3.4.0.3   
six              1.12.0    
tornado          5.1.1     
typing           3.6.6     
tzlocal          1.5.1     
urllib3          1.24.1    
voluptuous       0.11.5    
wheel            0.32.3
```

**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8266 board, NodeMCU v3 (but this is probably not relevant)

**Affected component:**

Custom Output -> https://esphomelib.com/esphomeyaml/components/output/custom.html

**Description of problem:**
The yaml configuration seems correct (copy/pasting from the documentation),
but the "run" fails with a ```[type] is an invalid option for [output.custom].``` error.
If I remove the ```type``` configuration, the "run" fails, correctly complaining about the missing mandatory param.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: testoutput
  platform: ESP8266
  board: nodemcuv2
  includes:
    - my_output.h

wifi:
  ssid: 'WIFI'
  password: 'PASSWORD'

# disable serial logging
logger:
  baud_rate: 0

# Enable Home Assistant API, disable the autoreboot
api:
  reboot_timeout: 0s

ota:

mqtt:
  broker: 10.0.0.1
  discovery: true
  discovery_retain: false

output:
- platform: custom
  type: float
  lambda: |-
    auto my_custom_float_output = new MyCustomFloatOutput();
    App.register_component(my_custom_float_output);
    return {my_custom_float_output};

  outputs:
    id: custom_float

```
my_output.h
```
#include "esphomelib.h"
using namespace esphomelib;

class MyCustomFloatOutput : public Component, public output::FloatOutput {
 public:
  void setup() override {
    // This will be called by App.setup()
    pinMode(5, OUTPUT);
  }

  void write_state(float state) override {
    // state is the amount this output should be on, from 0.0 to 1.0
    // we need to convert it to an integer first
    int value = state * 1024;
    analogWrite(5, value);
  }
};

```

**Traceback (if applicable):**

```
INFO Reading configuration...
Failed config

output.custom: [source testoutput.yaml:27]
  platform: custom
  
  [type] is an invalid option for [output.custom].
  type: float
  lambda: |-
    auto my_custom_float_output = new MyCustomFloatOutput();
    App.register_component(my_custom_float_output);
    return {my_custom_float_output};
  
  'platform' is a required option for [outputs].
  outputs:  [source testoutput.yaml:35]
    id: custom_float
```

**Additional information:**
