### ISSUE TITLE
Compile -> Ter

### ISSUE THREAD

**Issue by ioudeveldhuis** [OttoWinter/esphomeyaml#349]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP32

**Affected component:**
N/A

**Description of problem:**
When compiling the yaml below from the ESPHome Dashboard, the process stops with : Terminated process. 
No firmware can be downloaded after this.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: crazylongname
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'obnoxiousssid'
  password: 'totallyobviouspassword'
  id: my_wifi

esp32_ble_tracker:
  scan_interval: 300s

binary_sensor:
```

**Traceback (if applicable):**
N/A

**Additional information:**
https://imgur.com/a/38SHZ3Y

**Comment by OttoWinter** [comment]
I've seen this error before. I think it's related to the system that's running esphomeyaml somehow crashing (due to lack of resources, or some error in the compiler provided by espressif)

Just to confirm, what _system_ is this error happening on? Is it a RPi B (v1)? Anyway, the compiler is supplied by espressif (+ pre-compiled by platformio), and so I have no control over this part of the compilation process.

**Comment by ioudeveldhuis** [comment]
The system Hass.io is running on (docker) is a Netgear ReadyNas RN314.
I am able to compile the following yaml file but that is without the _ble stuff which I need.

```
esphomeyaml:
  name: crazylongname
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'obnoxiousssid'
  password: 'totallyobviouspassword'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'XXXXX'

ota:
  password: 'XXXXX'
```
