### ISSUE TITLE
Devices get discovered with .local

### ISSUE THREAD

**Issue by frog32** [OttoWinter/esphomeyaml#376]
**Operating environment (Hass.io/Docker/pip/etc.):**

hassio 0.86.0b1
**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8266
**Affected component:**

API

**Description of problem:**
Home Assistant discovers ESP home devices with .local even if domain is set to .lan

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  ssid: 'WIFI'
  password: '123456'
  domain: .lan
```

**Traceback (if applicable):**

```

```

**Additional information:**
