### ISSUE TITLE
4CH Pro R1 not working (bootloop)

### ISSUE THREAD

**Issue by peterforeman** [OttoWinter/esphomeyaml#381]
**Operating environment (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266/Board/Sonoff):**

Sonoff 4CH Pro R1

```
ESP Chip Id 10442015
Flash Chip Id 0x144051
Flash Size 1024kB
```

**Affected component:**

"Generic Sonoff"

**Description of problem:**
Uploading compiled firmware on my Tasmota-flash Sonoff 4CH Pro R1 creates a bootloop. The device never connects to WiFi anymore. Tried flashing via OTA (first time), and several times via serial. I tried the ESP8285 board (which is in the 4CH Pro R1) as well as the esp8266 board config. Nothing worked. Flashed Tasmota binary again which worked instantly (even remembered the settings).

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: 4chpro
  platform: ESP8266
  board: esp8285
  board_flash_mode: dout
```

**Traceback (if applicable):**

```
Not available yet, will update asap with serial logging.
```

**Additional information:**

**Comment by meijerwynand** [comment]
Greetings, 

I am not sure about the difference in the 4CH and 4CH Pro. I have the former and flashed it today without any issue.

Here is the config I use.

```yaml
esphomeyaml:
  name: ghrotto
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  esphomelib_version: 1.10.1

...

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ## use fast_connect to connect to hidden WiFi SSID
  fast_connect: true

```
