### ISSUE TITLE
Deep Sleep settings: can't use run_duration and run_cycles in the same time

### ISSUE THREAD

**Issue by oncleben31** [OttoWinter/esphomeyaml#39]
According to documentation we can use both parameters: 
```
To use deep_sleep first specify how long the node should be active, i.e. how long it should check sensor values and report them, using the run_duration and run_cycles options. If you use both in your configuration, any time either one of them is finished, the node will go into deep sleep mode.
```
In my case:
```
esphomeyaml:
  name: capteur_piscine
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: '192.168.1.28'
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

# Example configuration entry
dallas:
  - id: dallas_hub1
    pin: 4
    update_interval: 1s

# Individual sensors
sensor:
  - platform: dallas
    dallas_id: "dallas_hub1"
    address: 0x9C0417C1A988FF28
    name: "Température Piscine"
    icon: "mdi:oil-temperature"
    expire_after: "1:02"
    availability:

deep_sleep:
  run_duration: 20s
  run_cycles: 15
  sleep_duration: 1h
```
Seems to not work, the node go to deep sleep before the first cycle.
