### ISSUE TITLE
Hassio addon not working

### ISSUE THREAD

**Issue by ioudeveldhuis** [OttoWinter/esphomeyaml#43]
I have create 2 yaml files for my sonoff modules but when I press compile or validate buttons I get a terminated process message and nothing is done. I have not attached the module yet to flash because I want to migrate from Tasmota to this.

My yaml file looks like this:

```yaml
esphomeyaml:
  name: Sonoff2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'XXXXXXXXX'
  password: 'XXXXXXXXXXX'

mqtt:
  broker: 'XXXX.XXXXXXXXXXXX.XXX'
  username: ''
  password: ''

# Enable logging
logger:

ota:
  password: 'XXXXXX'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
  - platform: status
    name: "Sonoff Basic Status"

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    name: "Sonoff Basic Green LED"
    output: basic_green_led
```

**Comment by tonertiffi** [comment]
I have create 1 yaml files for my sonoff modules but when i upload the sonoff.bin file (using a usb to serial flash programmer esptool.exe -vv -cb 115200 -cp com11 -ca 0x00000 -bz 1m -bm dout -cf sonoff.bin ,also logged into the web interface upload firmware says its ok )
Unfortunately nothing happens just 1 blink of the led and nothing.
the hardware is a sonoff basic 1 relay esp8266
the bin creates 100% validate is also 100%

any help would be a blessing tried so may thing already

config file in esphomeyaml

esphomeyaml:
  name: sonoff01
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'my router ssid'
  password: 'password of router'
  
  manual_ip:
    static_ip: 192.x.x.x
    gateway: 192.x.x.x
    subnet: 255.255.255.0  

mqtt:
  broker: 'server ip of hassio'
  username: 'my username'
  password: 'my password'

# Enable logging
logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "sonoff01 Basic Button"
  - platform: status
    name: "sonoff01 Basic Status"

switch:
  - platform: gpio
    name: "sonoff01 Basic Relay"
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "sonoff01 Basic Green LED"
    output: basic_green_led

**Comment by OttoWinter** [comment]
@tonertiffi What specifically is not working? Does it not connect to WiFi/MQTT or does nothing show up in Home Assistant? The one short blink of the LED is telling me that esphomelib is at least starting up - maybe the WiFi/MQTT connection is failing?

The first step would be to view the esphomelib debug logs. Through the HassIO web interface, you can do this by clicking on the logs button (if you have it connected via USB, make sure you select `/dev/ttyUSB<something>` in the top navigation bar). Does something show up there?

Also, if you have the Arduino IDE installed or have a serial monitor, you can try starting a serial port with baud rate 115200. The logs should definitely help with debugging the issue.

**Comment by tonertiffi** [comment]
Hi OttoWinter I have made progress still not completely there, debug .it logs into Mqtt I added the web server so I can log into it an do the basic turn on relay led on board still a no go, even from web page.Hassio nothing showing. Any suggestions would be much appreciated. Thanks in advance

**Comment by OttoWinter** [comment]
@tonertiffi You can enable AP mode using the `ap:` option here: https://esphomelib.com/esphomeyaml/components/wifi.html

So do I understand this correctly?
 1. You can see the MQTT logs?
   * If not, that most probably means that the WiFi/MQTT ssid/server/password settings might be wrong.
    * If you're using `hassio.local` for the `mqtt.broker` option, consider using a static IP instead. Some routers do not like `hassio.local`
 2. The web server is not reachable, even though `web_server:` is in the configuration?
   * This would probably mean that the WiFi settings are not correct - or your router is somehow blocking the connection.
 3. Or alternatively, you cannot control *switches* through the web server.
   * This is a known bug in 1.6.2 (see https://github.com/OttoWinter/esphomelib/issues/68) - I've fixed it but for now you have to [use the latest dev version](https://esphomelib.com/esphomeyaml/guides/faq.html#how-do-i-use-the-latest-bleeding-edge-version) to not have this bug
 4. The Home Assistant frontend is not showing the sensors/relays.
   * This could be, for example, be because [MQTT Discovery](https://esphomelib.com/esphomeyaml/guides/faq.html#how-do-i-use-the-latest-bleeding-edge-version) is not explicitly enabled in the Home Assistant configuration.

**Comment by tonertiffi** [comment]
Hi OttoWinter,

Thank you for your help,the suggestions, worked 100% got it working thank you very much.

If I could be so bold and ask you 1 more thing,
I have no idea how to do it,i would like to pull the relay in and led green to turn on at the same time, as this is a good visual indication that the relay is on. I do see them separate in my config file but how to combine them in 1.

Kind regards
Tonertiffi

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by OttoWinter** [comment]
Well that's certainly very **bold**, even a bit *italic* 😉

So the way I would do that is by using a template switch like this:

```yaml
switch:
  - platform: gpio
    # ...
    id: switch1
  - platform: gpio
    # ...
    id: switch2
  - platform: template
    name: "My Switch"
    turn_on_action:
      - switch.turn_on:
          id: switch1
      - switch.turn_on:
          id: switch2
    turn_off_action:
      - switch.turn_off:
          id: switch1
      - switch.turn_off:
          id: switch2
    optimistic: true
```
