### ISSUE TITLE
Easy control of RGB LED controler ?

### ISSUE THREAD

**Issue by vincegre** [OttoWinter/esphomeyaml#44]
Hi

I'm using these Wifi LED strips controler based on ESP:
![espleds1](https://user-images.githubusercontent.com/3164888/41189659-c736dac8-6bd1-11e8-9348-a084f24f8de3.jpg)
It's fairly basic and use one GPIO for each color (R/G/B). Is it me or it's a little overcomplicated for basic control as I need to declare each color output like that:

```
output:
  - platform: gpio
    pin: 25
    id: 'color_red'
```
and then:

```
light:
  - platform: rgb
    name: "Living Room Lights"
    red: color_red
    green: color_green
    blue: color_blue
```
Isn't it possible to directly declare GPIO in light platform ?

Thanks

Vincèn

**Comment by OttoWinter** [comment]
You need to use the `esp8266_pwm` output platform. The GPIO output platform can only produce **binary** signals whereas RGB lights require a floating point output.

See the note here: https://esphomelib.com/esphomeyaml/components/light/rgb.html

> The RGB light platform only works with float outputs that can output any light intensity percentage like the ESP32 LEDC or ESP8266 PWM components and does not work with output platforms like the GPIO Output.

So in your case it would be:

```yaml
output:
  - platform: esp8266_pwm
    pin: 25
    id: 'color_red'
 # Same for other outputs

light:
  - platform: rgb
    name: "Living Room Lights"
    red: color_red
    green: color_green
    blue: color_blue
```

**Comment by vincegre** [comment]
Thanks so I did that config file for my controler:
```
esphomeyaml:
  name: sdb_light
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'myssid'
  password: 'mypass'

mqtt:
  broker: '192.168.1.8'
  username: 'myuser'
  password: 'mypass'

# Enable logging
logger:

ota:

output:
  - platform: esp8266_pwm
    pin: GPIO05
    id: 'color_red'
  - platform: esp8266_pwm
    pin: GPIO14
    id: 'color_green'
  - platform: esp8266_pwm
    pin: GPIO12
    id: 'color_blue'

light:
  - platform: rgb
    name: "Barre de LEDs"
    red: color_red
    green: color_green
    blue: color_blue
```
But once rebooted and connected to MQTT/HA, only a switch shows up in HA, no RGB control ???
