### ISSUE TITLE
Mqtt Availability option error

### ISSUE THREAD

**Issue by alesurli** [OttoWinter/esphomeyaml#59]
Hi, i've installed new 1.7 release but when i configure availability in mqtt as documented:

```
mqtt:
  broker: 'xxx.xxx.xxx.xxx'
  username: 'xxxx'
  password: 'xxxxx'
  availability: 

```
when i compile it returns me the following error:

Failed config
  mqtt:
    - Invalid config for [mqtt]: [availability] is an invalid option for [mqtt]. Check: mqtt->availability.
