### ISSUE TITLE
Integrate RCSwitch

### ISSUE THREAD

**Issue by sh0rez** [OttoWinter/esphomeyaml#65]
Hey!

I would like to integrate the [RCSwitch](https://github.com/sui77/rc-switch) library into esphomeyaml, to use its TriState functionality for 433mhz based wall plugs.

I HAVE seen the built in functionality for 433mhz of esphomeyaml but it wasnt able to satisfy me, as the RAW type of the data is quite hard to handle compared to basic TriState encoding. And the RCSwitch lib is working like a charm for over two years now and the wheel shouldn't need to be reinvented.

So I just thought I should be able to reimplement the RemoteTransmitterSwitch using it, but this seems to be harder than thought due to a total lack of documentation. I was unable to find anything about custom output components or at least a reference implementation of an output component.

I imagine the result as follows:
```yaml
#File: home.yaml

#[...]

switch:
  - platform: rc_switch
    name: "bedroom_lamp"
    on_tristate: "F0FF00FFFF0F" #example TriState value to turn on
    off_tristate: "F0FF00FFFFF0" #example TriState value to turn on

rc_switch:
  pin: D7
  protocol: 1 #optional: RCSwitch.setProtocol()
  pulse_length: 305 #optional: RCSwitch.setPulseLength()
  
```

So what would be the right way of doing this?
