### ISSUE TITLE
change icon

### ISSUE THREAD

**Issue by mefizto** [OttoWinter/esphomeyaml#66]
how can i change the icon, i try:

`light:
  - platform: rgb
    name: "Luz de Escritorio"
    icon: "mdi: track-light"
    red: output_component1
    green: output_component2
    blue: output_component3`

 but it doesnt work, it cant validate

**Comment by brandond** [comment]
Did you try it without a space in the icon value?
```yaml
light:
  - platform: rgb
    icon: "mdi:track-light"
```
```
