### ISSUE TITLE
Unstable (MQTT) connection - Sonoff T1 2CH

### ISSUE THREAD

**Issue by Boosik** [OttoWinter/esphomeyaml#89]
Hi, 
I'm experiencing a extremely unstable (MQTT?) connection on multiple Sonoff T1 2CH. Using Home Assistant MQTT discovery. Both Switches use this same config with only difference being name (bedroom/bathroom) and fan/light names.
I tried to experiment with keepalive interval (tried 5s, 10s, 15s, 30s, 60s) but that made no difference.
This issue doesn't occur instantly but approximately after 3-12 hours after flashing and persists untill reflash (I did not tried restart).
I also tried to remove GPIO12 and GPIO5 sensors that didn't help either.
I also tried to put the switches right next to my router to test if it could be caused by weak wifi signal but the issue persists even then.
I think it is caused by either my config or by bug in esphomeyaml as I was using Sonoff Tasmota before migrating to esphomeyaml and everything was fine.

I'm using Mosquitto on RPi3 as MQTT server.

```
esphomeyaml:
  name: bedroom
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'redacted'
  password: 'redacted'

mqtt:
  broker: 'redacted'
  username: 'redacted'
  password: 'redacted'
  port: redacted
  
output:
  - platform: gpio
    pin: 12
    id: light
  - platform: gpio
    pin: 5
    id: fan
  - platform: gpio
    pin: 13
    id: led
    inverted: true

binary_sensor:
  - platform: gpio
    id: light_sensor
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - light.toggle:
            id: light_light
  - platform: gpio
    id: fan_sensor
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - fan.toggle:
            id: fan_fan
  - platform: gpio
    id: output_sensor_1
    pin:
      number: GPIO12
      mode: OUTPUT
    on_press:
      then:
        - light.turn_on:
            id: light_led
    on_release:
      if:
        lambda: 'return !id(output_sensor_2).value;'
      then:
        - light.turn_off:
            id: light_led
  - platform: gpio
    id: output_sensor_2
    pin:
      number: GPIO5
      mode: OUTPUT
    on_press:
      then:
        - light.turn_on:
            id: light_led
    on_release:
      if:
        lambda: 'return !id(output_sensor_1).value;'
      then:
        - light.turn_off:
            id: light_led
  
light:
  - platform: binary
    id: light_light
    name: Ložnice
    output: light
  - platform: binary
    id: light_led
    output: led
    
fan:
  - platform: binary
    id: fan_fan
    name: Ložnice
    output: fan

logger:

ota:
```
