### ISSUE TITLE
DHT sensor GPIO pin is not properly set

### ISSUE THREAD

**Issue by simonszu** [OttoWinter/esphomeyaml#9]
I have some problems with setting up a DHT22 sensor. After making sure that the hardware is fine, it is definitely a software issue. I dug into some files, and noticed the following. This is the sensor definition in the YAML:
```
sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Schlafzimmer Temperatur"
    humidity:
      name: "Schlafzimmer Luftfeuchtigkeit"
    update_interval: 15s
```
The pin ist set to D4, as this is the official D1 mini DHT22 shield. Unfortunately, after compiling the firmware, i only get `NaN` values, so i looked in the generated code. The DHT22 sensor is set up like following:
```
  auto dht_sensor = App.make_dht_sensor("Schlafzimmer Temperatur", "Schlafzimmer Luftfeuchtigkeit", 0, 15000);
  dht_sensor.dht->set_dht_model(DHT::DHT22);
```

If i interpret esphomelib's API documentation correctly, the third argument of `make_dht_sensor` should be the sensor's pin - which is set to 0, contrary to the YAML's definition of D4. The documentation of esphomeyaml looks like that one has to specify `D4` and not only `4`. However, i have noticed that, if i specify `4` as the pin, it is correctly parsed and written in the source file - but, of course, the ESP fails to communicate with the DHT due to the wrong pin. 

So, either i have not fully understood the config file format (especially after taking a look at `pins.py`) or there is a bug...?
