### ISSUE TITLE
ESP32_Touch only works while using setup_mode true

### ISSUE THREAD

**Issue by nemmeh** [OttoWinter/esphomeyaml#91]
When setup_mode is set to true
`esp32_touch:
  setup_mode: true`

on_press works, however when setup_mode: false, on_press no longer triggers.

Am I missing something?

**Comment by diplix** [comment]
thats exactly what i found. to (kind of) work around this, i left the setup_mode on and disabled logging:

```
logger:
  level: NONE
esp32_touch:
  setup_mode: True
binary_sensor:
  - platform: esp32_touch
    name: "bar"
    pin: GPIO27
    threshold: 540
```
