### ISSUE TITLE
switch.on_turn_... actions causing failure to boot

### ISSUE THREAD

**Issue by Renegade605** [OttoWinter/esphomeyaml#9881]
### The problem

When attempting to add switch.on_turn_on/off actions, some cause the chip to fail boot. ESPHome web shows it disconnected, all entities are unavailable in Home Assistant, and on_boot action is never executed, but a new config can still be flashed OTA.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2025.3.3

### What platform are you using?

ESP32-IDF

### Board

Apollo DEV-1

### Component causing the issue

switch

### YAML Config

```yaml
# Define Project
substitutions:
  name: thermostat
  version: "0.1"
  device_description: ${name} made by DGR - version ${version}.

esphome:
  name: ${name}
  friendly_name: Thermostat
  comment: Thermostat on Apollo DEV-1
  platformio_options: 
    board_build.flash_mode: dio
  
  project:
    name: "DGR.Thermostat"
    version: "${version}"
  
  on_boot:
    then:
      - light.turn_on:
          id: rgb_onboard_light
          effect: "Fast Flash"
          red: 1.0
          green: 0
          blue: 0
      

# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermostat Fallback Hotspot"
    password: !secret wifi_password
  
  on_connect:
    then:
      - light.turn_on:
          id: rgb_onboard_light
          effect: "None"
          brightness: 0.5
          red: 1.0
          green: 0
          blue: 0

captive_portal:

web_server:
  port: 80

# Switches
switch:
  - platform: gpio
    pin: GPIO4
    id: relay_heater
    name: "Furnace Heat"
    on_turn_on: 
      then:
        - switch.turn_on: relay_blower
        - light.turn_on: 
            id: rgb_onboard_light
            effect: "Slow Pulse"
            brightness: 1.0
            red: 1.0
            green: 1.0
            blue: 0.9
#    on_turn_off: 
#      then:
#        - light.turn_on: 
#            id: rgb_onboard_light
#            effect: "Slow Pulse"
#            red: 0
#            green: 1.0
#            blue: 0
    
  - platform: gpio
    pin: GPIO5
    id: relay_blower
    name: "Blower Fan"
#    on_turn_on: 
#      then:
#        - if: 
#            condition:
#              - switch.is_off: relay_heater
#            then: 
#              - light.turn_on: 
#                  id: rgb_onboard_light
#                  effect: "Slow Pulse"
#                  red: 0
#                  green: 1.0
#                  blue: 0
    on_turn_off: 
      then:
        - switch.turn_off: relay_heater
#        - light.turn_on: 
#            id: rgb_onboard_light
#            effect: "None"
#            brightness: 0.5
#            red: 1.0
#            green: 0
#            blue: 0

# onboard LED using pin GPIO3 as shown below
light:
  - platform: esp32_rmt_led_strip
    id: rgb_onboard_light
    name: "RGB Onboard Light"
    pin: GPIO3
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 0.5
          max_brightness: 1.0
      - pulse:
          name: "Fast Flash"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 0.2
          max_brightness: 1.0

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: homeassistant
    entity_id: sensor.hallway_climate_temperature
    id: hallway_temperature
    name: "Hallway Temperature"
    device_class: temperature
    state_class: measurement
    internal: false
    on_value_range: 
      - below: 20.4
        then: 
          - switch.turn_on: relay_heater
      - above: 20.4
        then:
          - switch.turn_off: relay_blower
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

In the 2 switch entries, there are commented out sections. Uncommenting any one of these sections causes the issue (ie. trying to enable the on_turn_off action of switch.relay_heater).

Also tried with arduino framework instead of esp-idf, same behaviour.

**Comment by Renegade605** [comment]
After realizing I could get logs over USB, I have determined the cause.

The switch.on_turn_off is triggered on boot, the light.turn_on action causes a kernel panic because (I assume) it is not yet initialized.

(I was incorrect that enabling the on_turn_on trigger of the second switch caused the same failure, that one is actually fine.) 

Am I missing something here? Are triggers really intended to execute so early in the boot process that other components aren't ready yet? Does the light.turn_on action really not check if the target is ready? Why doesn't it handle the exception gracefully?

A ton of searching has yielded no obvious condition I can add that checks if these components are ready before calling them.

**Comment by randybb** [comment]
Exactly, it is not initialized yet. you need to change priority, so this will be executed a bit later.

```yaml
esphome:
  on_boot:
    priority: -100
    then:
      ...
```
