### ISSUE TITLE
[Feature Request] Add Automation Conditions language to Actions

### ISSUE THREAD

**Issue by inforsgit** [OttoWinter/esphomeyaml#99]
The Automations Conditions language (if: then:) in the YAML of an Automation is a really powerful tool. However, it appears that this is not allowed to be included in an Action block (for example, the Template Cover). While this can be implemented by making a Lambda in the Action block, it would be much easier as a user to just use pure YAML. Could this be something that is straightforward to implement?

As an example, here is a chunk of a Cover Template YAML with the proposed format (identical to the Automations Conditions):

```yaml
cover:
  - platform: template
    name: "Awning"
    id: awning
    open_action:
      #Turn off the power relay if it is on
      - if:
          lambda: 'return id(power_relay).value;'
        then:
          #Turn off the power relay
          - switch.turn_off:
              id: power_relay
          #Wait for power to fall
          - delay: 300ms
      #Switch the direction relay if necessary
      - if:
          lambda: 'return !id(power_relay).value;'
        then:
          #Set the direction relay
          - switch.turn_on:
              id: direction_relay
          #Wait for relay to switch
          - delay: 300ms
      #Turn on the power relay
      - switch.turn_on:
          id: power_relay
```
